SylLink_App/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("syllink/", include("syllink.urls")),
    path("admin/", admin.site.urls),
]

syllink/urls.py
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.urls import path

app_name = "syllink"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('upload/', views.upload_file, name='upload'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

syllink/models.py
from django.db import models

# Create your models here.

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class SyllabusUploader(models.Model):
    description = models.CharField(max_length=255, blank=True)
    syllabus = models.FileField(upload_to=user_directory_path)

syllink/forms.py
from django import forms
from .models import SyllabusUploader

class SyllabusUploaderForm(forms.ModelForm):
    class Meta:
        model = SyllabusUploader
        fields = ('description', 'syllabus', )

syllink/views.py
from django.shortcuts import redirect, render
from django.views import generic

from .forms import SyllabusUploaderForm


class IndexView(generic.ListView):
    template_name = "syllink/index.html"

    def get_queryset(self):
        """Return the last five published questions."""
        return None

def upload_file(request):
    if request.method == 'POST':
        form = SyllabusUploaderForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = SyllabusUploaderForm()
    return render(request, 'syllink/upload_file.html', {
        'form': form
    })

syllink/templates/syllink/index.html
{% load static %}

<!-- <link rel="stylesheet" href="{% static 'polls/style.css' %}"> -->
<ul>
    <!-- url 'namespace:name of path'-->
    <li><a href="{% url 'syllink:upload' %}">Click here to upload a file</a></li>
</ul>

syllink/templates/syllink/upload_file.html
{% load static %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'syllink:index' %}">Return to home</a></p>
{% endblock %}